app = "twinkle-toes"
primary_region = "iad"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[build.resources]
  cpus = 1
  cpu_kind = 'shared'
  memory = "256MB"

   
